name: Restful Booking API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t restful-booking-tests .

      - name: Run tests inside Docker
        run: docker run --rm restful-booking-tests

      - name: Upload Allure report
        uses: actions/upload-artifact@v4   # Updated from v3 to v4
        with:
          name: allure-report
          path: target/allure-report
