name: CI - RestfulBookingAPITests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # allow manual trigger

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Docker image
        run: docker build -t restful-booking-tests .

      - name: Run tests in Docker (keep container)
        run: docker run --name restful-tests-container restful-booking-tests || true

      - name: Copy Allure results
        run: docker cp restful-tests-container:/app/allure-results ./allure-results || true

      - name: Cleanup container
        run: docker rm restful-tests-container || true

      - name: Upload allure-results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
