name: CI - RestfulBookingAPITests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # allow manual trigger

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build & run tests inside Docker
      - name: Build Docker image
        run: docker build -t restful-booking-tests .

      - name: Run tests in Docker
        run: docker run --rm restful-booking-tests

      # Upload Allure results (from Docker container)
      - name: Copy Allure results
        run: docker cp $(docker ps -alq):/app/target/allure-results ./allure-results || true

      - name: Upload allure-results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report