name: CI - RestfulBookingAPITests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Docker image
        run: docker build -t restful-booking-tests .

      - name: Run tests in Docker
        run: docker run --name restful-tests-container restful-booking-tests || true

      - name: Generate Allure HTML report
        run: docker exec restful-tests-container \
          bash -c "allure generate target/allure-results -o target/allure-report --clean" || true

      - name: Copy Allure report to host
        run: docker cp restful-tests-container:/app/target/allure-report ./allure-report || true

      - name: Cleanup Docker container
        run: docker rm restful-tests-container || true

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
